theme: jekyll-theme-cayman
title: Reflexia Docs
description: Model-Based Reflex Agents Without Coding

navigation:
  - name: Home
    link: /
  - name: Getting Started
    link: /index.html
  - name: Adding Intelligence
    link: /intelligence/index.html
    subitems:
      - name: Creating Chip Groups
        link: /intelligence/chip-groups.html
      - name: Adding Chips
        link: /intelligence/chips.html
      - name: Defining Conditions
        link: /intelligence/conditions.html
      - name: Using Variables
        link: /intelligence/variables.html
      - name: Managing Attributes
        link: /intelligence/attributes.html
      - name: Defining Actions
        link: /intelligence/actions.html
  - name: Connecting to a Messaging App
    link: /terminals/index.html
  - name: Advanced Topics
    link: /advanced/index.html
    subitems:
      - name: Advanced Database
        link: /advanced/advanced-database.html
